alter table Album_Item drop constraint FK444EB323939793BB;
alter table Album_Item drop constraint FK444EB3239A392D7B;
alter table album drop constraint FK5897E6FE62B7365;
alter table album drop constraint FK5897E6FD399B7F;
alter table album drop constraint FK5897E6F760730B7;
alter table album drop constraint FK5897E6F919301A4;
alter table collection drop constraint FK9835AE9E919301A4;
alter table media_item drop constraint FK739B128E1A6ACDEC;
alter table media_item drop constraint FK739B128E2E6186E2;
alter table media_item drop constraint FK739B128EA032A193;
alter table media_item drop constraint FK739B128EC9E5DEE2;
alter table media_item_rating drop constraint FK3599406E4866CE76;
alter table media_item_rating drop constraint FK3599406E4A192480;
alter table metadata drop constraint FKE52D7B2FFCE2A6CF;
alter table metadata drop constraint FKE52D7B2FE1CA8FD4;
alter table metadata drop constraint FKE52D7B2F122A473A;
alter table theme drop constraint FK69375C9919301A4;
alter table user_comment drop constraint FK939585EBD9705906;
alter table user_comment drop constraint FK939585EB55B8CC7A;
alter table user_tag drop constraint FKF022FD26BC04F398;
alter table user_tag drop constraint FKF022FD264F77499F;
alter table users drop constraint FK6A68E08B9F85DC4;
alter table users drop constraint FK6A68E081A6ACDEC;
alter table users drop constraint FK6A68E08B18A531B;
drop table Album_Item;
drop table Locale;
drop table album;
drop table collection;
drop table media_item;
drop table media_item_rating;
drop table media_item_type;
drop table metadata;
drop table theme;
drop table time_zone;
drop table user_comment;
drop table user_tag;
drop table users;
drop table hibernate_unique_key;
create table Album_Item (Album_Item_Hjid bigint not null, MediaItem_Item_Hjchildid bigint not null, Album_Item_Hjindex integer not null, primary key (Album_Item_Hjid, Album_Item_Hjindex));
create table Locale (Hjid bigint not null, Hjtype varchar(255) not null, Ordering integer, Code varchar(255), Name_ varchar(255), primary key (Hjid));
create table album (AlbumId bigint not null, Hjtype varchar(255) not null, Theme bigint, Owner_ bigint, Comment_ varchar(2048), AllowFeed smallint not null, Poster bigint, AllowAnonymous smallint not null, AnonymousKey varchar(96), AllowOriginal smallint not null, AlbumDate timestamp, SortMode integer, Name_ varchar(255) not null, AllowBrowse smallint not null, ModifyDate timestamp, CreationDate timestamp not null, Album_Album_Hjid bigint, Album_Album_Hjindex integer, primary key (AlbumId));
create table collection (CollectionId bigint not null, Hjtype varchar(255) not null, Owner_ bigint, Comment_ varchar(2048), Path_ varchar(255) not null, Name_ varchar(128) not null, ModifyDate timestamp, CreationDate timestamp not null, primary key (CollectionId));
create table media_item (ItemId bigint not null, Hjtype varchar(255) not null, Hits integer not null, Height integer not null, TzDisplay varchar(40) not null, MediaType bigint, Description varchar(2048), Tz varchar(40) not null, Width integer not null, Path_ varchar(255) not null, Mime varchar(64) not null, DisplayOrder integer not null, Name_ varchar(128) not null, UseIcon smallint not null, ModifyDate timestamp, CreationDate timestamp not null, FileSize bigint not null, ItemDate timestamp, Collection_Item_Hjid bigint, Collection_Item_Hjindex integer, primary key (ItemId));
create table media_item_rating (RatingId bigint not null, Hjtype varchar(255) not null, RatingUser bigint, Rating smallint not null, CreationDate timestamp not null, MediaItem_UserRating_Hjid bigint, MediaItem_UserRating_Hjindex integer, primary key (RatingId));
create table media_item_type (TypeId bigint not null, Hjtype varchar(255) not null, name varchar(64) not null, primary key (TypeId));
create table metadata (Hjid bigint not null, Hjtype varchar(255) not null, mkey varchar(64) not null, Value_ varchar(255), MediaItem_Metadata_Hjid bigint, MediaItem_Metadata_Hjindex integer, MediaItemType_Field_Hjid bigint, MediaItemType_Field_Hjindex integer, User__Metadata_Hjid bigint, User__Metadata_Hjindex integer, primary key (Hjid));
create table theme (ThemeId bigint not null, Hjtype varchar(255) not null, Owner_ bigint, BasePath varchar(255) not null, Description varchar(2048), Author varchar(64), Name_ varchar(128) not null unique, ModifyDate timestamp, AuthorEmail varchar(128), CreationDate timestamp not null, primary key (ThemeId));
create table time_zone (Code varchar(40) not null, Hjtype varchar(255) not null, Ordering integer not null, TimeOffset integer not null, Name_ varchar(40), primary key (Code));
create table user_comment (CommentId bigint not null, Hjtype varchar(255) not null, CommentingUser bigint, Comment_ varchar(2048) not null, Approved smallint, CreationDate timestamp not null, Commenter varchar(255), MediaItem_UserComment_Hjid bigint, MediaItem_UserComment_Hjindex integer, primary key (CommentId));
create table user_tag (TagId bigint not null, Hjtype varchar(255) not null, Tag varchar(2048) not null, TaggingUser bigint not null, CreationDate timestamp not null, MediaItem_UserTag_Hjid bigint, MediaItem_UserTag_Hjindex integer, primary key (TagId));
create table users (UserId bigint not null, Hjtype varchar(255) not null, Quota integer, DiskUsage bigint, Language_ varchar(2) not null, Login varchar(128) not null unique, ThumbnailSetting_Quality varchar(255), ThumbnailSetting_Size_ varchar(255), Password_ varchar(128) not null, Email varchar(255) not null unique, Tz varchar(40) not null, AnonymousKey varchar(64), DefaultTheme bigint, BrowseTheme bigint, ViewSetting_Quality varchar(255), ViewSetting_Size_ varchar(255), AccessLevel integer, Country varchar(3) not null, Name_ varchar(128) not null, ModifyDate timestamp, CreationDate timestamp not null, primary key (UserId));
alter table Album_Item add constraint FK444EB323939793BB foreign key (Album_Item_Hjid) references album;
alter table Album_Item add constraint FK444EB3239A392D7B foreign key (MediaItem_Item_Hjchildid) references media_item;
alter table album add constraint FK5897E6FE62B7365 foreign key (Theme) references theme;
alter table album add constraint FK5897E6FD399B7F foreign key (Album_Album_Hjid) references album;
alter table album add constraint FK5897E6F760730B7 foreign key (Poster) references media_item;
alter table album add constraint FK5897E6F919301A4 foreign key (Owner_) references users;
alter table collection add constraint FK9835AE9E919301A4 foreign key (Owner_) references users;
alter table media_item add constraint FK739B128E1A6ACDEC foreign key (Tz) references time_zone;
alter table media_item add constraint FK739B128E2E6186E2 foreign key (TzDisplay) references time_zone;
alter table media_item add constraint FK739B128EA032A193 foreign key (Collection_Item_Hjid) references collection;
alter table media_item add constraint FK739B128EC9E5DEE2 foreign key (MediaType) references media_item_type;
alter table media_item_rating add constraint FK3599406E4866CE76 foreign key (MediaItem_UserRating_Hjid) references media_item;
alter table media_item_rating add constraint FK3599406E4A192480 foreign key (RatingUser) references users;
alter table metadata add constraint FKE52D7B2FFCE2A6CF foreign key (MediaItem_Metadata_Hjid) references media_item;
alter table metadata add constraint FKE52D7B2FE1CA8FD4 foreign key (MediaItemType_Field_Hjid) references media_item_type;
alter table metadata add constraint FKE52D7B2F122A473A foreign key (User__Metadata_Hjid) references users;
alter table theme add constraint FK69375C9919301A4 foreign key (Owner_) references users;
alter table user_comment add constraint FK939585EBD9705906 foreign key (CommentingUser) references users;
alter table user_comment add constraint FK939585EB55B8CC7A foreign key (MediaItem_UserComment_Hjid) references media_item;
alter table user_tag add constraint FKF022FD26BC04F398 foreign key (TaggingUser) references users;
alter table user_tag add constraint FKF022FD264F77499F foreign key (MediaItem_UserTag_Hjid) references media_item;
alter table users add constraint FK6A68E08B9F85DC4 foreign key (DefaultTheme) references theme;
alter table users add constraint FK6A68E081A6ACDEC foreign key (Tz) references time_zone;
alter table users add constraint FK6A68E08B18A531B foreign key (BrowseTheme) references theme;
create table hibernate_unique_key ( next_hi integer );
insert into hibernate_unique_key values ( 0 );
