alter table Album_Item drop constraint FK444EB323939793BB;
alter table Album_Item drop constraint FK444EB3239A392D7B;
alter table album drop constraint FK5897E6FE62B7365;
alter table album drop constraint FK5897E6FD399B7F;
alter table album drop constraint FK5897E6F760730B7;
alter table album drop constraint FK5897E6F919301A4;
alter table collection drop constraint FK9835AE9E919301A4;
alter table media_item drop constraint FK739B128E1A6ACDEC;
alter table media_item drop constraint FK739B128E2E6186E2;
alter table media_item drop constraint FK739B128EA032A193;
alter table media_item drop constraint FK739B128EC9E5DEE2;
alter table media_item_rating drop constraint FK3599406E4866CE76;
alter table media_item_rating drop constraint FK3599406E4A192480;
alter table metadata drop constraint FKE52D7B2FFCE2A6CF;
alter table metadata drop constraint FKE52D7B2FE1CA8FD4;
alter table metadata drop constraint FKE52D7B2F122A473A;
alter table theme drop constraint FK69375C9919301A4;
alter table user_comment drop constraint FK939585EBD9705906;
alter table user_comment drop constraint FK939585EB55B8CC7A;
alter table user_tag drop constraint FKF022FD26BC04F398;
alter table user_tag drop constraint FKF022FD264F77499F;
alter table users drop constraint FK6A68E08B9F85DC4;
alter table users drop constraint FK6A68E081A6ACDEC;
alter table users drop constraint FK6A68E08B18A531B;
drop table Album_Item;
drop table Locale;
drop table album;
drop table collection;
drop table media_item;
drop table media_item_rating;
drop table media_item_type;
drop table metadata;
drop table theme;
drop table time_zone;
drop table user_comment;
drop table user_tag;
drop table users;
drop sequence hibernate_sequence;
create table Album_Item (Album_Item_Hjid int8 not null, MediaItem_Item_Hjchildid int8 not null, Album_Item_Hjindex int4 not null, primary key (Album_Item_Hjid, Album_Item_Hjindex));
create table Locale (Hjid int8 not null, Hjtype varchar(255) not null, Ordering int4, Code varchar(255), Name_ varchar(255), primary key (Hjid));
create table album (AlbumId int8 not null, Hjtype varchar(255) not null, Theme int8, Owner_ int8, Comment_ varchar(2048), AllowFeed bool not null, Poster int8, AllowAnonymous bool not null, AnonymousKey varchar(96), AllowOriginal bool not null, AlbumDate timestamp with time zone, SortMode int4, Name_ varchar(255) not null, AllowBrowse bool not null, ModifyDate timestamp with time zone, CreationDate timestamp with time zone not null, Album_Album_Hjid int8, Album_Album_Hjindex int4, primary key (AlbumId));
create table collection (CollectionId int8 not null, Hjtype varchar(255) not null, Owner_ int8, Comment_ varchar(2048), Path_ varchar(255) not null, Name_ varchar(128) not null, ModifyDate timestamp with time zone, CreationDate timestamp with time zone not null, primary key (CollectionId));
create table media_item (ItemId int8 not null, Hjtype varchar(255) not null, Hits int4 not null, Height int4 not null, TzDisplay varchar(40) not null, MediaType int8, Description varchar(2048), Tz varchar(40) not null, Width int4 not null, Path_ varchar(255) not null, Mime varchar(64) not null, DisplayOrder int4 not null, Name_ varchar(128) not null, UseIcon bool not null, ModifyDate timestamp with time zone, CreationDate timestamp with time zone not null, FileSize int8 not null, ItemDate timestamp with time zone, Collection_Item_Hjid int8, Collection_Item_Hjindex int4, primary key (ItemId));
create table media_item_rating (RatingId int8 not null, Hjtype varchar(255) not null, RatingUser int8, Rating int2 not null, CreationDate timestamp with time zone not null, MediaItem_UserRating_Hjid int8, MediaItem_UserRating_Hjindex int4, primary key (RatingId));
create table media_item_type (TypeId int8 not null, Hjtype varchar(255) not null, name varchar(64) not null, primary key (TypeId));
create table metadata (Hjid int8 not null, Hjtype varchar(255) not null, mkey varchar(64) not null, Value_ varchar(255), MediaItem_Metadata_Hjid int8, MediaItem_Metadata_Hjindex int4, MediaItemType_Field_Hjid int8, MediaItemType_Field_Hjindex int4, User__Metadata_Hjid int8, User__Metadata_Hjindex int4, primary key (Hjid));
create table theme (ThemeId int8 not null, Hjtype varchar(255) not null, Owner_ int8, BasePath varchar(255) not null, Description varchar(2048), Author varchar(64), Name_ varchar(128) not null unique, ModifyDate timestamp with time zone, AuthorEmail varchar(128), CreationDate timestamp with time zone not null, primary key (ThemeId));
create table time_zone (Code varchar(40) not null, Hjtype varchar(255) not null, Ordering int4 not null, TimeOffset int4 not null, Name_ varchar(40), primary key (Code));
create table user_comment (CommentId int8 not null, Hjtype varchar(255) not null, CommentingUser int8, Comment_ varchar(2048) not null, Approved bool, CreationDate timestamp with time zone not null, Commenter varchar(255), MediaItem_UserComment_Hjid int8, MediaItem_UserComment_Hjindex int4, primary key (CommentId));
create table user_tag (TagId int8 not null, Hjtype varchar(255) not null, Tag varchar(2048) not null, TaggingUser int8 not null, CreationDate timestamp with time zone not null, MediaItem_UserTag_Hjid int8, MediaItem_UserTag_Hjindex int4, primary key (TagId));
create table users (UserId int8 not null, Hjtype varchar(255) not null, Quota int4, DiskUsage int8, Language_ varchar(2) not null, Login varchar(128) not null unique, ThumbnailSetting_Quality varchar(255), ThumbnailSetting_Size_ varchar(255), Password_ varchar(128) not null, Email varchar(255) not null unique, Tz varchar(40) not null, AnonymousKey varchar(64), DefaultTheme int8, BrowseTheme int8, ViewSetting_Quality varchar(255), ViewSetting_Size_ varchar(255), AccessLevel int4, Country varchar(3) not null, Name_ varchar(128) not null, ModifyDate timestamp with time zone, CreationDate timestamp with time zone not null, primary key (UserId));
alter table Album_Item add constraint FK444EB323939793BB foreign key (Album_Item_Hjid) references album;
alter table Album_Item add constraint FK444EB3239A392D7B foreign key (MediaItem_Item_Hjchildid) references media_item;
alter table album add constraint FK5897E6FE62B7365 foreign key (Theme) references theme;
alter table album add constraint FK5897E6FD399B7F foreign key (Album_Album_Hjid) references album;
alter table album add constraint FK5897E6F760730B7 foreign key (Poster) references media_item;
alter table album add constraint FK5897E6F919301A4 foreign key (Owner_) references users;
alter table collection add constraint FK9835AE9E919301A4 foreign key (Owner_) references users;
alter table media_item add constraint FK739B128E1A6ACDEC foreign key (Tz) references time_zone;
alter table media_item add constraint FK739B128E2E6186E2 foreign key (TzDisplay) references time_zone;
alter table media_item add constraint FK739B128EA032A193 foreign key (Collection_Item_Hjid) references collection;
alter table media_item add constraint FK739B128EC9E5DEE2 foreign key (MediaType) references media_item_type;
alter table media_item_rating add constraint FK3599406E4866CE76 foreign key (MediaItem_UserRating_Hjid) references media_item;
alter table media_item_rating add constraint FK3599406E4A192480 foreign key (RatingUser) references users;
alter table metadata add constraint FKE52D7B2FFCE2A6CF foreign key (MediaItem_Metadata_Hjid) references media_item;
alter table metadata add constraint FKE52D7B2FE1CA8FD4 foreign key (MediaItemType_Field_Hjid) references media_item_type;
alter table metadata add constraint FKE52D7B2F122A473A foreign key (User__Metadata_Hjid) references users;
alter table theme add constraint FK69375C9919301A4 foreign key (Owner_) references users;
alter table user_comment add constraint FK939585EBD9705906 foreign key (CommentingUser) references users;
alter table user_comment add constraint FK939585EB55B8CC7A foreign key (MediaItem_UserComment_Hjid) references media_item;
alter table user_tag add constraint FKF022FD26BC04F398 foreign key (TaggingUser) references users;
alter table user_tag add constraint FKF022FD264F77499F foreign key (MediaItem_UserTag_Hjid) references media_item;
alter table users add constraint FK6A68E08B9F85DC4 foreign key (DefaultTheme) references theme;
alter table users add constraint FK6A68E081A6ACDEC foreign key (Tz) references time_zone;
alter table users add constraint FK6A68E08B18A531B foreign key (BrowseTheme) references theme;
create sequence hibernate_sequence;
